[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
wasm-bindgen = "0.2"
reqwest = { version = "0.12.5", features = ["json"] }
